<a href="https://colab.research.google.com/github/betuuulsan/numpy_notlar-/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
import numpy as np
#Numpy, Python programlama dilinde kullanılan güçlü bir sayısal hesaplama kütüphanesidir.
#Temelde çok boyutlu diziler ve matrisler üzerinde yüksek performanslı matematiksel işlemler gerçekleştirmek için tasarlanmıştır.
#Numpy, bilimsel hesaplamalarda, veri analizinde ve makine öğrenmesi gibi alanlarda geniş bir kullanım alanına sahiptir.

In [11]:
#bir numpy array oluşturalım:
dizi = np.array([1,2,3])
print(dizi)

[1 2 3]


In [12]:
#yukarıdaki numpy array'in tipine bakalım
dizi = np.array([1,2,3])
print(type(dizi))

<class 'numpy.ndarray'>


In [5]:


dizi = np.array([[1,2,3],[4,5,6]])   #Bu satırda, bir Numpy dizisi oluşturuyoruz. İki satır ve üç sütundan oluşan bir matris. Matrisin elemanları 1'den 6'ya kadar ardışık sayılardır.
yeni_dizi = dizi.reshape(3,2)
# reshape fonksiyonunu kullanarak dizi adlı orijinal diziyi yeniden şekillendiriyoruz. Yani, orijinal matrisi 3 satır ve 2 sütundan oluşan yeni bir matrise dönüştürüyoruz.


print(yeni_dizi) # Son olarak orijinal matrisin yeniden şekillendirilmiş hali olan yeni_dizi'yi ekrana yazdıracaktır.

[[1 2]
 [3 4]
 [5 6]]


In [8]:
#Şimdi yukarıda yaptığımız örneğin daha farklısını yapalım.
dizi = np.array([[1,2,3,4,5,6,7,8,9,10],[11,12,13,14,15,16,17,18,19,20]]) #bu sefer Numpy dizimizi daha uzun yapalım.
yeni_dizi = dizi.reshape(4,5)
print(yeni_dizi)

#sayılar ve Numpy dizisi üzerinde değişiklikler yaparak farklı şekillerde yeniden boyutlandırabilirsiniz :))

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [9]:
#np.arange() FONKSİYONUNUN KULLANIMI
#np.arange() fonksiyonu, Numpy kütüphanesinde belirtilen bir aralıktaki sayıları içeren bir dizi (array) oluşturmak için kullanılır.
#Bu fonksiyon, genellikle belirli bir başlangıç değeri, bitiş değeri ve isteğe bağlı olarak adım değeri alarak çalışır.

#şimdi birkaç örnek yazalım:
dizi1 = np.arange(3) #başlangıç varsayılanı: 0 , adım sayısı varsayılanı: 1
dizi2 = np.arange(3,8) #başlangıç varsayılanı: 5 , adım sayısı varsayılanı: 1
dizi3 = np.arange(1,11,3) #başlangıç: 1, adım sayısı: 3, bitiş: 11

print("Dizi1:", dizi1)
print("Dizi2:", dizi2)
print("Dizi3:", dizi3)


Dizi1: [0 1 2]
Dizi2: [3 4 5 6 7]
Dizi3: [ 1  4  7 10]


In [ ]:
#ndarray.ndim İLE BİR FONKSİYONUN BOYUTUNU BULMAK
#ndarray.ndim özelliği, bir Numpy dizisinin boyut sayısını (dimension) döndüren bir özelliktir.
#Yani, bir dizinin kaç boyutlu olduğunu belirler. Her boyut bir eksen (axis) olarak adlandırılır.

#İşte bu özelliğin kullanımı:
dizi = np.array([[1, 2, 3], [4, 5, 6]])
boyut = dizi.ndim
print(boyut)
#Bu kod, dizi adlı iki boyutlu bir Numpy dizisi oluşturur. Sonra, ndim özelliğini kullanarak bu dizinin boyut sayısını elde eder ve ekrana yazdırır.
#Bu, dizi'nin iki boyutlu bir dizi olduğunu gösterir. Eğer dizi tek boyutlu olsaydı, ndim özelliği 1'i döndürürdü.
#Eğer daha fazla boyuta sahip bir dizi olsaydı, örneğin üç boyutlu bir dizi, ndim 3'ü döndürürdü ve boyut sayısı arttıkça bu şekilde devam ederdi.
#Bu özellik, Numpy dizilerinin yapısını anlamak ve program içinde dinamik olarak çalışmak için önemlidir.
